// <auto-generated />
namespace UnitOfWork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class userSettingsModelChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userSettingsModelChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201605010934237_userSettingsModelChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
