// <auto-generated />
namespace UnitOfWork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class added_identity_framework_maybe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_identity_framework_maybe));
        
        string IMigrationMetadata.Id
        {
            get { return "201604241531049_added_identity_framework_maybe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
